### PR TITLE
Fetch sha1 dynamically, support macosx64

### PR DESCRIPTION
**Pull request by CLRN**
Hi, this is to cover https://github.com/chase/awrit/blob/e7ad5be6d2eee3c87f5f8aac254ceae08f2fe3e0/CMakeLists.txt#L20 and to fix build on macos 64 bit, unfortunately I can't verify if the build passes on other platforms.

### CODE REVIEW

**Comment by chase** [comment]
@CLRN thanks for the PR!

I noticed this uses `jq` to handle the JSON, and I'm not sure if I want to introduce another dependency to build `awrit`.

Since CMake 3.19, has supported querying JSON: https://cmake.org/cmake/help/latest/command/string.html#json

It might not be sufficient, but if you have time, I'd appreciate if you could make this PR use that instead.

**Comment by CLRN** [comment]
Hey, yeah, that was my concern as well, unfortunately CMake doesn't have any functionality for filtering JSON. But let me see how messy it would be without it.

**Comment by CLRN** [comment]
@chase done, please have a look, thanks.

**Review by chase — APPROVED** [review]
Works perfectly, thanks for the contribution!

**Pull request merged**
